#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Dec  5 20:30:30 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade
from cineplusequipo import MyFrame
# begin wxGlade: extracode
# end wxGlade


class taquilla(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: taquilla.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((770, 731))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(196, 240, 255))
        self.panel_1.SetForegroundColour(wx.Colour(50, 153, 204))

         #Variables de instancia de la Ventana 3
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=""
        self.subtotalTaquilla=0

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("png-transparent-earth-planet-silhouette-stencil-solar-system-earth-logo-sticker-saturn.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Subheading"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("png-transparent-earth-planet-silhouette-stencil-solar-system-earth-logo-sticker-saturn.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "*Estrenos")
        label_8.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Heading"))
        sizer_2.Add(label_8, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("spr.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(bitmap_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cbxInter = wx.CheckBox(self.panel_1, wx.ID_ANY, "Interestelar")
        grid_sizer_6.Add(self.cbxInter, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_7 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("trol.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bitmap_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cbxPaw = wx.CheckBox(self.panel_1, wx.ID_ANY, "Paw Patrol La Pelicula")
        grid_sizer_7.Add(self.cbxPaw, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios")
        label_9.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Display"))
        sizer_2.Add(label_9, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_12, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        sizer_12.Add(label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Interestelar:")
        sizer_12.Add(label_11, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "la patrulla")
        sizer_12.Add(label_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_13, 1, wx.EXPAND, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios Disponibles")
        sizer_13.Add(label_22, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 3, 0, 0)
        sizer_13.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "1:00pm")
        grid_sizer_9.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "2:15")
        grid_sizer_9.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "4:00")
        grid_sizer_9.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 3, 0, 0)
        sizer_13.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.rbHorario4 = wx.RadioButton(self.panel_1, wx.ID_ANY, "8:00")
        grid_sizer_10.Add(self.rbHorario4, 0, 0, 0)

        self.rbHorario5 = wx.RadioButton(self.panel_1, wx.ID_ANY, "10:00")
        grid_sizer_10.Add(self.rbHorario5, 0, 0, 0)

        self.rbHorario6 = wx.RadioButton(self.panel_1, wx.ID_ANY, "3:00")
        grid_sizer_10.Add(self.rbHorario6, 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_15, 1, wx.EXPAND, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_15.Add(label_25, 0, 0, 0)

        label_26 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_15.Add(label_26, 0, 0, 0)

        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_16, 1, wx.EXPAND, 0)

        label_27 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_16.Add(label_27, 0, 0, 0)

        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_14, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala")
        sizer_14.Add(label_14, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala(1)")
        sizer_14.Add(label_15, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala(2)")
        sizer_14.Add(label_16, 0, 0, 0)

        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_17, 1, wx.EXPAND, 0)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18.Add(sizer_19, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        sizer_19.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos  ")
        grid_sizer_11.Add(label_23, 0, 0, 0)

        self.spAdultos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_11.Add(self.spAdultos, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(1, 2, 0, 0)
        sizer_19.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_24 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Niños")
        grid_sizer_12.Add(label_24, 0, 0, 0)

        self.spNinos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_12.Add(self.spNinos, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        grid_sizer_13.Add(self.btnCancelar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Confirmar")
        grid_sizer_13.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cbxInter.Bind(wx.EVT_CHECKBOX, self.seleccionPelicula1)
        self.cbxPaw.Bind(wx.EVT_CHECKBOX, self.seleccionPelicula2)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.rbHorario4.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario4)
        self.rbHorario5.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario5)
        self.rbHorario6.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario6)
        self.spAdultos.Bind(wx.EVT_SPINCTRL, self.calcularAdultos)
        self.spNinos.Bind(wx.EVT_SPINCTRL, self.clacularNinos)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.confirmarTaquilla)
        # end wxGlade

    def seleccionPelicula1(self, event):  # wxGlade: taquilla.<event_handler>
        self.peliculaseleccionada=self.cbxInter.GetLabelText()
        event.Skip()

    def seleccionPelicula2(self, event):  # wxGlade: taquilla.<event_handler>
        self.peliculaseleccionada=self.cbxPaw.GetLabelText()
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="1:00pm\nSala 1"
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="2:15pm\nSala 1"
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="4:00pm\nSala 1"
        event.Skip()

    def seleccionHorario4(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="8:00pm\nSala 2"
        event.Skip()

    def seleccionHorario5(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="10:00pm\nSala 2"
        event.Skip()

    def seleccionHorario6(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="3:00pm\nSala 2"
        event.Skip()

    def calcularAdultos(self, event):  # wxGlade: taquilla.<event_handler>
        self.adultos = int(self.spAdultos.GetValue())
        self.subtotal_a = self.adultos * 80
        self.subtotal=self.subtotal_a 
        event.Skip()

    def clacularNinos(self, event):  # wxGlade: taquilla.<event_handler>
        self.menores = int(self.spNinos.GetValue())
        self.subtotal_b = self.menores * 70
        self.subtotal=self.subtotal_a + self.subtotal_b
        event.Skip()

    #Creacion de la funcion para limpar para la taquilla
    def limpiarValores_Campos(self):

        # Limpiar los variables de Instancia
        self.peliculaseleccionada = ""
        self.horarioseleccionado = ""
        self.cantidad_adultos = 0
        self.cantidad_ninos = 0
        self.cbxInter.SetValue(False)
        self.cbxPaw.SetValue(False)
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.rbHorario4.SetValue(False)
        self.rbHorario5.SetValue(False)
        self.rbHorario6.SetValue(False)
        self.spAdultos.SetValue(0)
        self.spNinos.SetValue(0)
        self.subtotal1 = 0
        self.subtotal2 = 0
        self.subtotalTaquilla = 0
        self.infoTaquilla = ""

    def cancelarTaquilla(self, event):  # wxGlade: taquilla.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def confirmarTaquilla(self, event):  # wxGlade: taquilla.<event_handler>
        self.cantidad_adultos = self.spAdultos.GetValue()
        self.cantidad_ninos = self.spNinos.GetValue()
        # Aquí puedes agregar el código para procesar la confirmación de la taquilla
        pregunta=wx.MessageDialog(
        self,
        f"Confirmando taquilla: {self.cantidad_adultos} adultos ${self.subtotal_a}, {self.cantidad_ninos} niños ${self.subtotal_b}\nPelicula: {self.peliculaseleccionada}\nHorario: {self.horarioseleccionado}\nSubtotal: ${self.subtotal}\n\n¿Desea continuar?",
        "Confirmación",
        style=wx.YES_NO | wx.ICON_QUESTION
        )       
        respuesta=pregunta.ShowModal()
        if respuesta==wx.ID_YES:
            v3=MyFrame(self, wx.ID_ANY, "")
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta==wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class taquilla

class MyApp(wx.App):
    def OnInit(self):
        self.frame = taquilla(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
