#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec  4 07:23:52 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade
class Ventana4(wx.Frame):
    def __init__(self,parent,informacion="",subtotal=0,informacion2="",subtotal2=0):
        # begin wxGlade: Ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((632, 715))
        self.SetTitle("frame_3")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal
        self.infoDulceria=informacion2
        self.subtotalDulceria=subtotal2

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("planet-saturn-icon-design-vector.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Compra y cobro")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("planet-saturn-icon-design-vector.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Con que desea pagar")
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(label_3, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Tarjeta de debito ")
        grid_sizer_2.Add(label_8, 0, 0, 0)

        self.rbTarjeta = wx.RadioButton(self.panel_1, wx.ID_ANY, "")
        grid_sizer_2.Add(self.rbTarjeta, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Credito")
        grid_sizer_3.Add(label_5, 0, 0, 0)

        self.rbCredito = wx.RadioButton(self.panel_1, wx.ID_ANY, "")
        grid_sizer_3.Add(self.rbCredito, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Efectivo")
        grid_sizer_4.Add(label_6, 0, 0, 0)

        self.rbEfectivo = wx.RadioButton(self.panel_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.rbEfectivo, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pay pal")
        grid_sizer_5.Add(label_7, 0, 0, 0)

        self.rbPaypal = wx.RadioButton(self.panel_1, wx.ID_ANY, "")
        grid_sizer_5.Add(self.rbPaypal, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.btnCerrar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCerrar.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_6.Add(self.btnCerrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnConfirmar = wx.Button(self.panel_1, wx.ID_ANY, "Confirmar")
        self.btnConfirmar.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_6.Add(self.btnConfirmar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.rbTarjeta.Bind(wx.EVT_RADIOBUTTON, self.seleccionDebito)
        self.rbCredito.Bind(wx.EVT_RADIOBUTTON, self.seleccionCredito)
        self.rbEfectivo.Bind(wx.EVT_RADIOBUTTON, self.seleccionEfectivo)
        self.rbPaypal.Bind(wx.EVT_RADIOBUTTON, self.seleccionPaypal)
        self.btnCerrar.Bind(wx.EVT_BUTTON, self.cancelarTicket)
        self.btnConfirmar.Bind(wx.EVT_BUTTON, self.confirmarTicket)
        # end wxGlade

    def seleccionDebito(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox("Ha seleccionado pagar con Tarjeta de débito", "Método de pago", wx.OK | wx.ICON_INFORMATION)
        seleccion="Debito"
        event.Skip()
    def seleccionCredito(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox("Ha seleccionado pagar con Tarjeta de crédito", "Método de pago", wx.OK | wx.ICON_INFORMATION)
        seleccion="Credito"
        event.Skip()
    def seleccionEfectivo(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox("Ha seleccionado pagar en efectivo", "Método de pago", wx.OK | wx.ICON_INFORMATION)   
        seleccion="Efectivo"
        event.Skip()
    def seleccionPaypal(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox("Ha seleccionado pagar con PayPal", "Método de pago", wx.OK | wx.ICON_INFORMATION)
        seleccion="Paypal"
        event.Skip()

    def cancelarTicket(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox("La venta ha sido cancelada", "Cancelar Venta", wx.OK|wx.ICON_INFORMATION)
        wx.Exit()
        event.Skip()

    def confirmarTicket(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox(f"La venta ha sido confirmada", "Confirmar Venta", wx.OK|wx.ICON_INFORMATION)
        event.Skip()


class MyFrame(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((920, 670))
        self.SetTitle("frame_2")
        print(f"Datos de la ventana 2:\nInformacion: {informacion} \n")
        print(f"Subtotal: {subtotal}")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(205, 175, 255))

        #Variables de instancia de la Ventana 3
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(11, 1, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_1, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Personal:")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_3, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas chicas - Refresco chico.")
        grid_sizer_7.Add(label_4, 0, 0, 0)

        self.spComboPersonal = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_7.Add(self.spComboPersonal, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo Pareja:")
        label_5.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_8.Add(label_5, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Nachos medianos, Ref. mediano, sushi-12p.")
        grid_sizer_9.Add(label_6, 0, 0, 0)

        self.spComboPareja = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_9.Add(self.spComboPareja, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Combo BFF:")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_10.Add(label_7, 0, 0, 0)

        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 sandwich, 2 Ref. med, 2 dulces a elegir.")
        grid_sizer_11.Add(label_8, 0, 0, 0)

        self.spComboBFF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_11.Add(self.spComboBFF, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Combo Niños:")
        label_9.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_12.Add(label_9, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas chicas, Jugo chico (sabor a elegir).")
        grid_sizer_13.Add(label_10, 0, 0, 0)

        self.spComboNinos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_13.Add(self.spComboNinos, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "PIEZA UNICA")
        label_11.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_12.Add(label_11, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        grid_sizer_20 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "REFRESCOS")
        label_19.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_20.Add(label_19, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_22 = wx.GridSizer(1, 6, 0, 0)
        grid_sizer_20.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grande")
        grid_sizer_22.Add(label_16, 0, 0, 0)

        self.spRefrescosG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_22.Add(self.spRefrescosG, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mediano")
        grid_sizer_22.Add(label_17, 0, 0, 0)

        self.spRefrescosMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_22.Add(self.spRefrescosMd, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chico")
        grid_sizer_22.Add(label_18, 0, 0, 0)

        self.spRefrescosCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_22.Add(self.spRefrescosCh, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("refresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_17.Add(bitmap_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_21 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_2.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor:")
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_21.Add(label_12, 0, 0, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Naranja")
        grid_sizer_21.Add(label_13, 0, 0, 0)

        self.spSaborNara = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_21.Add(self.spSaborNara, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Manzana")
        grid_sizer_21.Add(label_14, 0, 0, 0)

        self.spSaborMan = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_21.Add(self.spSaborMan, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Coca-Cola")
        grid_sizer_21.Add(label_15, 0, 0, 0)

        self.spSaborCoca = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_21.Add(self.spSaborCoca, 0, 0, 0)

        grid_sizer_18 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        grid_sizer_23 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_18.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        label_24 = wx.StaticText(self.panel_1, wx.ID_ANY, "PALOMITAS")
        label_24.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_23.Add(label_24, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_26 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_23.Add(grid_sizer_26, 1, wx.EXPAND, 0)

        label_26 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes:")
        grid_sizer_26.Add(label_26, 0, 0, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_26.Add(self.spPalomitasG, 0, 0, 0)

        label_27 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas:")
        grid_sizer_26.Add(label_27, 0, 0, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_26.Add(self.spPalomitasMd, 0, 0, 0)

        label_28 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas:")
        grid_sizer_26.Add(label_28, 0, 0, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_26.Add(self.spPalomitasCh, 0, 0, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("palomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_25 = wx.GridBagSizer(0, 0)
        grid_sizer_2.Add(grid_sizer_25, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor:")
        label_20.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_25.Add(label_20, (0, 0), (1, 1), 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "Queso")
        grid_sizer_25.Add(label_21, (0, 1), (1, 1), 0, 0)

        self.spSaborQue = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_25.Add(self.spSaborQue, (0, 2), (1, 1), 0, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Mantequilla")
        grid_sizer_25.Add(label_22, (0, 3), (1, 1), 0, 0)

        self.spSaborMantequilla = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_25.Add(self.spSaborMantequilla, (0, 4), (1, 1), 0, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Natural")
        grid_sizer_25.Add(label_23, (0, 5), (1, 1), 0, 0)

        self.spSaborNatu = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_25.Add(self.spSaborNatu, (0, 6), (1, 1), 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_5 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "NACHOS")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_5.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_14 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_5.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes:")
        grid_sizer_14.Add(label_25, 0, 0, 0)

        self.spNachosG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_14.Add(self.spNachosG, 0, 0, 0)

        label_29 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas:")
        grid_sizer_14.Add(label_29, 0, 0, 0)

        self.spNachosMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_14.Add(self.spNachosMd, 0, 0, 0)

        label_30 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas:")
        grid_sizer_14.Add(label_30, 0, 0, 0)

        self.spNachosCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_14.Add(self.spNachosCh, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("nachos.png", wx.BITMAP_TYPE_ANY))
        bitmap_4.SetMinSize((70, 60))
        grid_sizer_4.Add(bitmap_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((150, 50))
        grid_sizer_1.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((150, 50))
        grid_sizer_1.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboPersonal.Bind(wx.EVT_SPINCTRL, self.calcularComboPersonal)
        self.spComboPareja.Bind(wx.EVT_SPINCTRL, self.calcularComboPareja)
        self.spComboBFF.Bind(wx.EVT_SPINCTRL, self.calcularComboBFF)
        self.spComboNinos.Bind(wx.EVT_SPINCTRL, self.calcularComboNinos)
        self.spRefrescosG.Bind(wx.EVT_SPINCTRL, self.calcularRefrescosG)
        self.spRefrescosMd.Bind(wx.EVT_SPINCTRL, self.calcularRefrescosMd)
        self.spRefrescosCh.Bind(wx.EVT_SPINCTRL, self.calcularRefrescosCh)
        self.spSaborNara.Bind(wx.EVT_SPINCTRL, self.calcularSaborNara)
        self.spSaborMan.Bind(wx.EVT_SPINCTRL, self.calcularSaborMan)
        self.spSaborCoca.Bind(wx.EVT_SPINCTRL, self.calcularSaborCoca)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spSaborQue.Bind(wx.EVT_SPINCTRL, self.calcularSaborQue)
        self.spSaborMantequilla.Bind(wx.EVT_SPINCTRL, self.calcularSaborMantequilla)
        self.spSaborNatu.Bind(wx.EVT_SPINCTRL, self.calcularSaborNatu)
        self.spNachosG.Bind(wx.EVT_SPINCTRL, self.calcularNachosG)
        self.spNachosMd.Bind(wx.EVT_SPINCTRL, self.calcularNachosMd)
        self.spNachosCh.Bind(wx.EVT_SPINCTRL, self.calcularNachosCh)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboPersonal(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spComboPersonal.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos Basicos"
        event.Skip()

    def calcularComboPareja(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spComboPareja.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos Pareja"
        event.Skip()

    def calcularComboBFF(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spComboBFF.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos BFF"
        event.Skip()

    def calcularComboNinos(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spComboNinos.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combo Niños"
        event.Skip()

    def calcularRefrescosG(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spRefrescosG.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Refrescos Grandes"
        event.Skip()

    def calcularRefrescosMd(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spRefrescosMd.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Refrescos Medianos"
        event.Skip()

    def calcularRefrescosCh(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spRefrescosCh.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Refrescos Chicos"
        event.Skip()

    def calcularSaborNara(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborNara.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Naranja"
        event.Skip()

    def calcularSaborMan(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborMan.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Manzana"
        event.Skip()

    def calcularSaborCoca(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborCoca.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Coca"
        event.Skip()
    def calcularPalomitasCh(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*30
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas Chicas"
        event.Skip()
    def calcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*50
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas Medianas"
        event.Skip()
    def calcularPalomitasG(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas Grandes"
        event.Skip()
    def calcularSaborQue(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborQue.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Queso"
        event.Skip()
    def calcularSaborMantequilla(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborMantequilla.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Mantequilla"
        event.Skip()

    def calcularSaborNatu(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spSaborNatu.GetValue())
        self.infoDulceria=self.infoDulceria + f"\n{numero} Sabor Natural"
        event.Skip()

    def calcularNachosG(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spNachosG.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Nachos Grandes"
        event.Skip()
    def calcularNachosMd(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spNachosMd.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Nachos Medianos"
        event.Skip()
    def calcularNachosCh(self, event):  # wxGlade: MyFrame.<event_handler>
        numero=int(self.spNachosCh.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.infoDulceria=self.infoDulceria + f"\n{numero} Nachos chicos"
        event.Skip()

    def LimpiarD(self):

        self.subtotalDulceria=0
        self.infoDulceria=""

        self.spComboPersonal.SetValue(0)
        self.spComboPareja.SetValue(0)
        self.spComboBFF.SetValue(0)
        self.spComboNinos.SetValue(0)
        self.spRefrescosG.SetValue(0)
        self.spRefrescosMd.SetValue(0)
        self.spRefrescosCh.SetValue(0)
        self.spSaborNara.SetValue(0)
        self.spSaborMan.SetValue(0)
        self.spSaborCoca.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spSaborQue.SetValue(0)
        self.spSaborMantequilla.SetValue(0)
        self.spSaborNatu.SetValue(0)
        self.spNachosG.SetValue(0)
        self.spNachosMd.SetValue(0)
        self.spNachosCh.SetValue(0)
        

    def limpiarDulceria(self, event):  # wxGlade: MyFrame.<event_handler>
        self.LimpiarD()
        event.Skip()
    def siguienteDulceria(self, event):  # wxGlade: MyFrame.<event_handler>
        pregunta=wx.MessageDialog(self,
        f"Confirmacion de dulceria.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        f"Subtotal Dulceria: ${self.subtotalDulceria}",
        "Dulceria",style=wx.YES_NO|wx.ICON_QUESTION)
        respuesta=pregunta.ShowModal()
        pregunta.Destroy()
        if respuesta==wx.ID_YES:
            v4= Ventana4(self, informacion=self.infoTaquilla,
                        subtotal=self.subtotalTaquilla,
                        informacion2=self.infoDulceria,
                        subtotal2=self.subtotalDulceria)
            v4.Show()
            self.LimpiarD()
            self.Hide()
        elif respuesta==wx.ID_NO:
            self.LimpiarD()
        event.Skip()
# end of class MyFrame

class taquilla(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: taquilla.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((770, 731))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(196, 240, 255))
        self.panel_1.SetForegroundColour(wx.Colour(50, 153, 204))

         #Variables de instancia de la Ventana 3
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=""
        self.subtotalTaquilla=0

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("png-transparent-earth-planet-silhouette-stencil-solar-system-earth-logo-sticker-saturn.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Subheading"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("png-transparent-earth-planet-silhouette-stencil-solar-system-earth-logo-sticker-saturn.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "*Estrenos")
        label_8.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Heading"))
        sizer_2.Add(label_8, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("spr.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(bitmap_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cbxInter = wx.CheckBox(self.panel_1, wx.ID_ANY, "Interestelar")
        grid_sizer_6.Add(self.cbxInter, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_7 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("trol.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bitmap_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cbxPaw = wx.CheckBox(self.panel_1, wx.ID_ANY, "Paw Patrol La Pelicula")
        grid_sizer_7.Add(self.cbxPaw, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios")
        label_9.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Display"))
        sizer_2.Add(label_9, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_12, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        sizer_12.Add(label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Interestelar:")
        sizer_12.Add(label_11, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "la patrulla")
        sizer_12.Add(label_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_13, 1, wx.EXPAND, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horarios Disponibles")
        sizer_13.Add(label_22, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 3, 0, 0)
        sizer_13.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "1:00pm")
        grid_sizer_9.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "2:15")
        grid_sizer_9.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "4:00")
        grid_sizer_9.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 3, 0, 0)
        sizer_13.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.rbHorario4 = wx.RadioButton(self.panel_1, wx.ID_ANY, "8:00")
        grid_sizer_10.Add(self.rbHorario4, 0, 0, 0)

        self.rbHorario5 = wx.RadioButton(self.panel_1, wx.ID_ANY, "10:00")
        grid_sizer_10.Add(self.rbHorario5, 0, 0, 0)

        self.rbHorario6 = wx.RadioButton(self.panel_1, wx.ID_ANY, "3:00")
        grid_sizer_10.Add(self.rbHorario6, 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_15, 1, wx.EXPAND, 0)

        label_25 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_15.Add(label_25, 0, 0, 0)

        label_26 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_15.Add(label_26, 0, 0, 0)

        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_16, 1, wx.EXPAND, 0)

        label_27 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_16.Add(label_27, 0, 0, 0)

        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8.Add(sizer_14, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala")
        sizer_14.Add(label_14, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala(1)")
        sizer_14.Add(label_15, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala(2)")
        sizer_14.Add(label_16, 0, 0, 0)

        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_17, 1, wx.EXPAND, 0)

        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18.Add(sizer_19, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        sizer_19.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos  ")
        grid_sizer_11.Add(label_23, 0, 0, 0)

        self.spAdultos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_11.Add(self.spAdultos, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(1, 2, 0, 0)
        sizer_19.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_24 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Niños")
        grid_sizer_12.Add(label_24, 0, 0, 0)

        self.spNinos = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_12.Add(self.spNinos, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        grid_sizer_13.Add(self.btnCancelar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Confirmar")
        grid_sizer_13.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cbxInter.Bind(wx.EVT_CHECKBOX, self.seleccionPelicula1)
        self.cbxPaw.Bind(wx.EVT_CHECKBOX, self.seleccionPelicula2)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.rbHorario4.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario4)
        self.rbHorario5.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario5)
        self.rbHorario6.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario6)
        self.spAdultos.Bind(wx.EVT_SPINCTRL, self.calcularAdultos)
        self.spNinos.Bind(wx.EVT_SPINCTRL, self.clacularNinos)
        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.confirmarTaquilla)
        # end wxGlade

    def seleccionPelicula1(self, event):  # wxGlade: taquilla.<event_handler>
        self.peliculaseleccionada=self.cbxInter.GetLabelText()
        event.Skip()

    def seleccionPelicula2(self, event):  # wxGlade: taquilla.<event_handler>
        self.peliculaseleccionada=self.cbxPaw.GetLabelText()
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="1:00pm\nSala 1"
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="2:15pm\nSala 1"
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="4:00pm\nSala 1"
        event.Skip()

    def seleccionHorario4(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="8:00pm\nSala 2"
        event.Skip()

    def seleccionHorario5(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="10:00pm\nSala 2"
        event.Skip()

    def seleccionHorario6(self, event):  # wxGlade: taquilla.<event_handler>
        self.horarioseleccionado="3:00pm\nSala 2"
        event.Skip()

    def calcularAdultos(self, event):  # wxGlade: taquilla.<event_handler>
        self.adultos = int(self.spAdultos.GetValue())
        self.subtotal_a = self.adultos * 80
        self.subtotal=self.subtotal_a 
        event.Skip()

    def clacularNinos(self, event):  # wxGlade: taquilla.<event_handler>
        self.menores = int(self.spNinos.GetValue())
        self.subtotal_b = self.menores * 70
        self.subtotal=self.subtotal_a + self.subtotal_b
        event.Skip()

    #Creacion de la funcion para limpar para la taquilla
    def limpiarValores_Campos(self):

        # Limpiar los variables de Instancia
        self.peliculaseleccionada = ""
        self.horarioseleccionado = ""
        self.cantidad_adultos = 0
        self.cantidad_ninos = 0
        self.cbxInter.SetValue(False)
        self.cbxPaw.SetValue(False)
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.rbHorario4.SetValue(False)
        self.rbHorario5.SetValue(False)
        self.rbHorario6.SetValue(False)
        self.spAdultos.SetValue(0)
        self.spNinos.SetValue(0)
        self.subtotal1 = 0
        self.subtotal2 = 0
        self.subtotalTaquilla = 0
        self.infoTaquilla = ""

    def cancelarTaquilla(self, event):  # wxGlade: taquilla.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def confirmarTaquilla(self, event):  # wxGlade: taquilla.<event_handler>
        self.cantidad_adultos = self.spAdultos.GetValue()
        self.cantidad_ninos = self.spNinos.GetValue()
        # Aquí puedes agregar el código para procesar la confirmación de la taquilla
        pregunta=wx.MessageDialog(
        self,
        f"Confirmando taquilla: {self.cantidad_adultos} adultos ${self.subtotal_a}, {self.cantidad_ninos} niños ${self.subtotal_b}\nPelicula: {self.peliculaseleccionada}\nHorario: {self.horarioseleccionado}\nSubtotal: ${self.subtotal}\n\n¿Desea continuar?",
        "Confirmación",
        style=wx.YES_NO | wx.ICON_QUESTION
        )       
        respuesta=pregunta.ShowModal()
        if respuesta==wx.ID_YES:
            v3=MyFrame(self, informacion=self.infoTaquilla,
                        subtotal=self.subtotalTaquilla
                        )
            v3.Show()
            self.Hide()
        elif respuesta==wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

class MyApp(wx.App):
    def OnInit(self):
        self.taquilla = taquilla(None, wx.ID_ANY, "")
        self.SetTopWindow(self.taquilla)
        self.taquilla.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
